apiVersion: v1
kind: ConfigMap
metadata:
  name: whisper-queue-reader-configmap
data:
  INPUT_BUCKET_NAME: <input_bucket_name>
  OUTPUT_BUCKET_NAME: <output_bucket_name>
  REGION: <region>
  SERVICE_ENDPOINT: <service_endpoint>
  QUEUE_ID: <queue_id>
  MAX_PARALLEL: <max_parallel>