FROM nvidia/cuda:12.8.0-cudnn-devel-oraclelinux8

WORKDIR /app

# Install image dependencies (for Python and whisper)

RUN dnf install -y python3.12 python3.12-pip python3.12-setuptools python3.12-pip-wheel gcc libffi-devel python3-devel openssl-devel

COPY requirements.txt requirements.txt

# Torch for cuda 12.8
RUN python3.12 -m pip install --pre torch==2.8.0.dev20250319  --index-url https://download.pytorch.org/whl/nightly/cu128

RUN python3.12 -m pip install -r requirements.txt

ENV LD_LIBRARY_PATH=/usr/local/lib/python3.12/site-packages/cusparselt/lib:$LD_LIBRARY_PATH

COPY whisper-queue.py /app

CMD ["python3.12", "whisper-queue.py"]